### ISSUE TITLE
Browser in desktop vs android 

### ISSUE THREAD

**Issue by jessicasFranco** [zakaton/Bose-Frames-Web-SDK#7]
Hello, 
I tried your demo and I struggled to connect my Bose in my computer's browser (chrome (I did enabled all the flags mentioned in this repository)). When I did it the same in the smartphone everything went smoothly. I want to ask if this is normal or if I need to change something in order to have it working in my desktop browser. 
When I tried to connect in my desktop browser I get the error "GATT operation not authorized". 

Best regards,

**Comment by zakaton** [comment]
Sorry for the late response - I don't need notifications for these things

Are you using the Bose 700's?

**Comment by jessicasFranco** [comment]
no problem. Yes I am using Bose 700's.

**Comment by zakaton** [comment]
I thought so - someone else had messaged me having the exact same problem.

I think the 700's have some "secure pairing" thing where you have to be connected naively or something using their app (I'm not quite sure since I don't have the 700's myself).

It works fine for the QC35's and the Frames, but as for the 700's unfortunately you'll have to stream from your smartphone to the browser using websockets or socket.io or something similar. Sorry about that :(

**Comment by cael-gomes** [comment]
OK, I was having the same problem as @jessicasFranco and figured out a way to make it work.

I'm using Windows 10 and Bose NC 700.

**Steps:** 

1. Make sure your Motion Detection is enabled on Bose Music App (Settings -> Power -> Motion Detection).

2. Remove all existing BTconnections BT from your headset (press and hold the BT button for 5+ seconds), as well as any BT connection to your headset on your PC

3. Add a new BT connection (Windows Key then "Bluetooth and other devices settings"). You want to connect to the LE-<device name> instead of the <device name>. This step is important! After you connect, instead of hearing the usual "Connected to <device>", you'll hear "Ready to connect" again.

4. Go to https://zakaton.github.io/Bose-Frames-Web-SDK/default.html#connecting-to-your-bose-ar-device, and click the Connect button. Your NC 700 should appear in the list with this name: LE-<device name> - Paired

5. Now open a new tab (do not close the tab mentioned in step 4!) and go to https://zakaton.github.io/Bose-Frames-Web-SDK/ and click the glasses button. You need to pick the same device as step 4.

That did the trick to me. It's rather strange, but I suppose there's something wrong with the connection mentioned in step 5.
